# -*- coding: utf-8 -*-
"""Lİbrary_Management_System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AXWTaw7W2m0qQLB_pcKYXuBn_AOGaY4O
"""

#library management system
class Library:
  def __init__(self, booksfile):
    self.booksfile = booksfile
    self.booksfile = open('books.txt', 'a+')

  def __del__(self):
    self.booksfile.close()

  def display_books(self):
    self.booksfile.seek(0)
    booksfile = open("books.txt" , "r")
    content = booksfile.read().splitlines()
    booksfile.close()
    for line in content:
       book_info = line.strip().split(",")
       print(f"title: {book_info[0]}, author: {book_info[1]}")

  def add_book(self):
    print("enter the book name:")
    name = input()
    print("enter the author:")
    author = input()
    print("enter the first release year:")
    year = str(input())
    print("enter the number of pages:")
    pages = str(input())
    bookstring = f"{name},{author},{year},{pages}\n"
    with open("books.txt", "a+") as booksfile:
      booksfile.seek(0)
      booksfile.write(bookstring)


  def remove_book(self):
    print("Please enter the name of the book you want to remove? : ")
    book_to_remove = input()
    self.booksfile.seek(0)
    book = []
    for line in self.booksfile:
      book_info = line.strip().split(",")
      if book_info[0] != book_to_remove:
        book.append(line)
    self.booksfile.seek(0)
    self.booksfile.truncate()
    self.booksfile.writelines(book)


lib = Library("books.txt")

while True:
  print("""   ***MENU***
  1) List Book
  2) Add Book
  3) Remove Book""")
  print("Which operation do you want to do? : ")
  operation = input()

  if operation == "1":
    lib.display_books()

  elif operation == "2" :
    lib.add_book()

  elif operation == "3" :
    lib.remove_book()

  elif operation == "Q" or operation == "q":
    break

  else :
    print("invalid operation!")